on:
  push:
    branches: [dev]
    paths:
      - 'factorial.py'
      - 'lint.py'

jobs:
  lint_and_run:
    name: Lint and Run Factorial Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Lint with pylint
        run: |
          pylint lint.py

      - name: Run Factorial Script
        run: python factorial.py
